### ISSUE TITLE
60. css的常用布局

### ISSUE THREAD

**Issue by ForeveHG** [ForeveHG/Frontend-Daily-Interview#62]

**Comment by ForeveHG** [comment]
圣杯布局和双飞翼布局

1. 解决的问题： 两种方式都是为了解决左右两栏固定，中间自适应的布局
2. 相同点：中间栏设置width:100%; 三栏都需要左浮动；左右两栏用margin负值移动到中间栏的位置，对中间栏形成了遮挡；
3. 不同点：不同的是在解决左右两栏对中间一栏遮挡的处理方式上，圣杯布局是用三栏的父元素设置padding-left和padding-right，然后将左右两栏position定位解决，双飞翼布局是在中间一栏的外层包裹一个元素，设置这个外层元素的左右padding，然后设置中间一栏的margin，留出左右两栏的位置，左右两栏通过负margin移动到两边
4. 实现方式

圣杯布局
```html
<div class="wrap">
    <div class="content"></div>
    <div class="left"></div>
    <div class="right"></div>
</div>
```
```css
.wrap {
    padding: 0 200px;
}
.content {
    width: 100%;
    height: 200px;
    background: red;
    float: left;
    
}
.left {
    width: 200px;
    height: 200px;
    background: green;
    float: left;
    margin-left: -100%;
    position: relative;
   left: -200px;
}
.right{
    width: 200px;
    height: 200px;
    background: green;
    float: left;
    margin-left: -200px;
    position: relative;
    right: -200px;
}
```
双飞翼
```html
<div class="content_wrap">
    <div class="content"></div>
</div>
<div class="left"></div>
<div class="right"></div>
```
```css
.content_wrap {
   padding: 0 200px;
}
.content {
    width: 100%;
    height: 200px;
    background: red;
    float: left;
    margin: 0 200px;
}
.left {
    width: 200px;
    height: 200px;
    background: green;
    float: left;
    margin-left: -100%;
}
.right{
    width: 200px;
    height: 200px;
    background: green;
    float: left;
    margin-left: -200px;
}
```
